-- Migration: Add short_label column to profile_research_interests
-- Stores a concise 2-5 word label generated by LLM for timeline display

ALTER TABLE profile_research_interests
ADD COLUMN IF NOT EXISTS short_label VARCHAR(100);

-- Add comment for documentation
COMMENT ON COLUMN profile_research_interests.short_label IS 'LLM-generated concise label (2-5 words) for timeline display';
