from fastapi import APIRouter, HTTPException, UploadFile, File, Form, BackgroundTasks
from fastapi.responses import FileResponse
import tempfile
import uuid
import os
from datetime import datetime

from ..dependencies import db, DB_URL
from ..tasks import task_manager

router = APIRouter(prefix="/api/settings/database", tags=["database"])

@router.get("/export")
async def export_database(background_tasks: BackgroundTasks):
    """Export the database as a compressed tar.gz file using the existing JSON export system."""
    try:
        from ...utils.db_migration.db_export import DatabaseExporter
        
        print("INFO:     Starting database export...")
        
        # Create timestamp for filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Create a temporary directory for the export files
        with tempfile.TemporaryDirectory() as temp_dir:
            export_dir = os.path.join(temp_dir, "export")
            
            # Use the existing DatabaseExporter
            exporter = DatabaseExporter(DB_URL, export_dir)
            
            print("INFO:     Exporting database tables...")
            # Export all data to JSON files
            papers_file = exporter.export_papers()
            podcasts_file = exporter.export_podcasts()
            newsletters_file = exporter.export_newsletters()
            metadata_file = exporter.create_metadata()
            
            # Create archive file outside temp directory to persist after context exit
            # Create data/temp directory if it doesn't exist
            os.makedirs("data/temp", exist_ok=True)
            archive_file = os.path.join("data/temp", f"theseus_backup_{timestamp}.tar.gz")
            
            print(f"INFO:     Creating archive at {archive_file}...")
            # Create compressed archive
            import tarfile
            with tarfile.open(archive_file, "w:gz") as tar:
                tar.add(export_dir, arcname=".")
        
        # Verify archive was created successfully
        if not os.path.exists(archive_file):
            raise HTTPException(status_code=500, detail="Archive file was not created successfully")
        
        archive_size = os.path.getsize(archive_file)
        if archive_size == 0:
            raise HTTPException(status_code=500, detail="Archive file is empty")
        
        print(f"INFO:     Export complete. Archive size: {archive_size / 1024 / 1024:.1f} MB")
        
        # Add a background task to clean up the file after 10 minutes (enough time for download)
        def cleanup_export_file(file_path: str):
            try:
                import time
                time.sleep(600)  # Wait 10 minutes
                if os.path.exists(file_path):
                    os.remove(file_path)
                    print(f"INFO:     Cleaned up export file: {file_path}")
            except Exception as e:
                print(f"Warning: Could not clean up export file {file_path}: {e}")
        
        background_tasks.add_task(cleanup_export_file, archive_file)
        
        # Return the archive file (temp directory is now cleaned up but archive persists)
        return FileResponse(
            archive_file,
            media_type="application/gzip",
            filename=f"theseus_backup_{timestamp}.tar.gz",
            headers={
                "Content-Disposition": f"attachment; filename=theseus_backup_{timestamp}.tar.gz",
                "Cache-Control": "no-cache, no-store, must-revalidate",
                "Pragma": "no-cache",
                "Expires": "0"
            }
        )
            
    except Exception as e:
        print(f"ERROR: Database export failed: {str(e)}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Database export failed: {str(e)}")

@router.post("/export-task")
async def start_database_export():
    """Start a background database export task."""
    task_id = str(uuid.uuid4())

    await task_manager.create_task(
        task_id=task_id,
        task_type="database_export",
        config={},
    )

    await task_manager.enqueue_task(task_manager.run_database_export_task, task_id)

    return {
        "task_id": task_id,
        "message": f"Database export started. Use WebSocket /ws/database-export/{task_id} for progress updates."
    }

@router.get("/export-task/{task_id}/download")
async def download_exported_database(task_id: str):
    """Download the archive generated by a completed export task."""
    from ..tasks import TaskStatus
    
    task = task_manager.get_task_status(task_id)
    if not task:
        raise HTTPException(status_code=404, detail=f"Task {task_id} not found")

    if task["status"] != TaskStatus.COMPLETED:
        raise HTTPException(status_code=400, detail=f"Task is not completed (current status: {task['status']})")

    result = task.get("result", {})
    archive_path = result.get("archive_path")
    if not archive_path or not os.path.exists(archive_path):
        raise HTTPException(status_code=404, detail="Export file not available")

    return FileResponse(
        archive_path,
        media_type="application/gzip",
        filename=os.path.basename(archive_path),
        headers={
            "Content-Disposition": f"attachment; filename={os.path.basename(archive_path)}",
            "Cache-Control": "no-cache, no-store, must-revalidate",
            "Pragma": "no-cache",
            "Expires": "0",
        },
    )

@router.post("/import")
async def import_database(
    background_tasks: BackgroundTasks,
    backup_file: UploadFile = File(...),
    import_mode: str = Form("merge", description="Import mode: 'merge' (default) or 'overwrite'")
):
    """Import a database from a compressed backup file using background task with progress updates."""
    try:
        if not backup_file.filename or not backup_file.filename.endswith(('.tar.gz', '.tgz')):
            raise HTTPException(
                status_code=400, 
                detail="Invalid file format. Please upload a .tar.gz or .tgz file."
            )
        
        if import_mode not in ["merge", "overwrite"]:
            raise HTTPException(
                status_code=400,
                detail="Invalid import mode. Must be 'merge' or 'overwrite'."
            )
        
        # Create a task ID for tracking
        task_id = str(uuid.uuid4())
        
        # Save the uploaded file to a temporary location
        temp_file_path = f"data/temp/{task_id}_import.tar.gz"
        os.makedirs(os.path.dirname(temp_file_path), exist_ok=True)
        
        with open(temp_file_path, "wb") as f:
            content = await backup_file.read()
            f.write(content)
        
        # Create the background task
        task_config = {
            "archive_path": temp_file_path,
            "import_mode": import_mode,
            "filename": backup_file.filename
        }
        
        await task_manager.create_task(
            task_id=task_id,
            task_type="database_import",
            config=task_config
        )
        
        await task_manager.enqueue_task(task_manager.run_database_import_task, task_id)
        
        return {
            "task_id": task_id,
            "message": f"Database import started. Use WebSocket /ws/database-import/{task_id} for progress updates."
        }
            
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database import failed: {str(e)}") 